import { useState, type FormEvent } from "react";
import type { ProviderSlot } from "../../api/providerSlotsApi";

interface Props { slots: ProviderSlot[]; onCreate: (startsAt: string, endsAt: string) => Promise<void>; onUpdate: (slot: ProviderSlot, startsAt: string, endsAt: string) => Promise<void>; onDelete: (slot: ProviderSlot) => Promise<void> }
const asInput = (iso: string) => iso.slice(0, 16);
export function SlotManagementPanel({ slots, onCreate, onUpdate, onDelete }: Props) {
  const [startsAt, setStartsAt] = useState(""); const [endsAt, setEndsAt] = useState(""); const [editing, setEditing] = useState<string>();
  async function create(event: FormEvent) { event.preventDefault(); await onCreate(new Date(startsAt).toISOString(), new Date(endsAt).toISOString()); setStartsAt(""); setEndsAt(""); }
  return <><form className="form-panel" onSubmit={create}><h2>Uj idosav</h2><label>Kezdete<input required type="datetime-local" value={startsAt} onChange={(event) => setStartsAt(event.target.value)} /></label><label>Vege<input required type="datetime-local" value={endsAt} onChange={(event) => setEndsAt(event.target.value)} /></label><button>Idosav letrehozasa</button></form><section aria-labelledby="slots-title"><h2 id="slots-title">Sajat idosavak</h2>{!slots.length ? <p role="status">Meg nincs rogzitett idosav.</p> : <ul className="slot-list">{slots.map((slot) => <li key={slot.id}>{editing === slot.id ? <EditSlot slot={slot} onSave={async (start, end) => { await onUpdate(slot, start, end); setEditing(undefined); }} onCancel={() => setEditing(undefined)} /> : <><span>{new Date(slot.startsAt).toLocaleString("hu-HU")} - {new Date(slot.endsAt).toLocaleTimeString("hu-HU", { hour: "2-digit", minute: "2-digit" })} ({slot.status})</span>{slot.status === "AVAILABLE" && <span><button type="button" onClick={() => setEditing(slot.id)}>Modositas</button><button type="button" onClick={() => onDelete(slot)}>Torles</button></span>}</>}</li>)}</ul>}</section></>;
}
function EditSlot({ slot, onSave, onCancel }: { slot: ProviderSlot; onSave: (start: string, end: string) => Promise<void>; onCancel: () => void }) { const [start, setStart] = useState(asInput(slot.startsAt)); const [end, setEnd] = useState(asInput(slot.endsAt)); return <form onSubmit={(event) => { event.preventDefault(); return onSave(new Date(start).toISOString(), new Date(end).toISOString()); }}><input aria-label="Modositott kezdet" type="datetime-local" value={start} onChange={(event) => setStart(event.target.value)} /><input aria-label="Modositott veg" type="datetime-local" value={end} onChange={(event) => setEnd(event.target.value)} /><button>Mentes</button><button type="button" onClick={onCancel}>Megse</button></form>; }